server:
  port: 8081
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never

legendme-users-svc:
  url: http://localhost:8080/legendme/users/create/google-user
  existByEmailUrl: http://localhost:8082/legendme/users/exist-by-email
  createLocalUrl: http://localhost:8080/legendme/users/create


google:
  client-id: ${CLIENT_ID}
  jwks-uri: https://www.googleapis.com/oauth2/v3/certs

app:
  X-Internal-Token:
    ${X-Internal-Token}
  jwt:
    issuer: legendme-login-svc
    secret: ${JWT_SECRET}
    access-exp-minutes: 60
    refresh-exp-days: 7

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet

  datasource:
    url: jdbc:mysql://localhost:3306/legendme_auth_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:legendme_auth}
    password: ${DB_PASSWORD:StrongPassw0rd!}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.boot: WARN
    org.springframework.web: WARN
    org.springframework.security: INFO
    org.apache.catalina: WARN
    org.apache.coyote: WARN
    org.hibernate: WARN